# DATASET:
#   PATH:
#     TFRECORDS : '/home/sparclab/ESCA/ThanhHo/train_on_pc/Data/dev_data_fan/tfrecord' 
#     NORMAL : '/home/sparclab/ESCA/ThanhHo/train_on_pc/Data/dev_data_fan/fan/train' 
#     ANOMALY : '/home/sparclab/ESCA/ThanhHo/train_on_pc/Data/dev_data_fan/fan/Anomaly'
#     TEST: '/home/sparclab/ESCA/ThanhHo/train_on_pc/Data/dev_data_fan/fan/Normal'

# TRAINING: 
#   LOG_FOLDER : '/home/sparclab/ESCA/ThanhHo/train_on_pc/Data/dev_data_fan/Results'
#   EPOCH : 75

# TRANSFER_LEARNING: 
#   # NORMAL_DATA_DIRS: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/tfrecord/train'
#   # ANOMALY_DATA_DIRS: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/tfrecord/anomaly'
#   BASED_WEIGHTS: '/home/sparclab/ESCA/ThanhHo/train_on_pc/Data/dev_data_fan/Results/saved_model/vq-vae'


# DATASET:
#   PATH:
#     TFRECORDS : '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/tfrecord' 
#     NORMAL : '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/fan/train' 
#     ANOMALY : '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/fan/source_test/Anomaly'
#     TEST: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/fan/source_test/Normal'

# TRAINING: 
#   LOG_FOLDER : '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/Results'
#   EPOCH : 75

# TRANSFER_LEARNING: 
#   # NORMAL_DATA_DIRS: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/tfrecord/train'
#   # ANOMALY_DATA_DIRS: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/tfrecord/anomaly'
#   BASED_WEIGHTS: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/Results/saved_model/vq-vae'


DATASET:
  PATH:
    TFRECORDS : 'D:\Desktop\Development\Py\ESCA\ESCA_v2\temp'
    NORMAL : 'D:\Desktop\Development\Py\ESCA\ESCA_v2\Dataset\audio_44.1k\intersection\normal' 
    ANOMALY : 'D:\Desktop\Development\Py\ESCA\ESCA_v2\Dataset\audio_44.1k\intersection\abnormal'
    # TEST: '/home/thanhho/Downloads/dev_data_ToyCar/ToyCar/source_test/Nomaly'

TRAINING: 
  LOG_FOLDER : 'D:\Desktop\Development\Py\ESCA\SCA_v2\Results'
